language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  global:
    - secure: "bJUK+FEBax3oKhFwwAbTFbMKUpicZKjonddgMUaXrFWE0V8Mm8tL2dPBAvjOZD5xpz5YEqnspJR34VjvHVc7QwwJ+M/KECB2olh4z/CKUi5OLiQd65chHaMSRyXOveAEEeoLCbXC0UzlydpWfBQtxKUX75cFHO8FOphQE+ruoFU="
    - secure: "Kb6Fb2EX9skkftvy63SDTCQSazBhn2RFVxYkSy9K1l0+qzi7dujalMuEVCwWZei6WdvpemzIvRx2lNM7Az5mOollTmLTSAUlcaaDNbO+vn4YJmXzgFoDELd+YZp1nRT1Aears/EK0P+uoAILOBfEm3kc/b7sql3upjit+khjHko="
    - CIBW_PLATFORM=linux
    - CIBW_SKIP="cp26-* cp33-*"
    - CIBW_BEFORE_BUILD="{pip} install -r requirements/wheel.txt"
sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -U pip
before_script: git clone https://github.com/pkgcore/pkgdist.git
script:
  - cp -av pkgdist/requirements/* requirements/
  - pip install -r requirements/ci.txt
  - tox -e travis
  - pkgdist/build-dist-files.sh
after_success:
  - tox -e coverage-report
  - codecov
