language: python
python:
    - 2.7
    - 3.3
    - 3.4
install:
    - pip install pytest-cov coveralls mock pylint
    - python setup.py install
script:
    - pushd build/lib*
    - py.test --cov chroot
after_success:
    # upload coverage data to coveralls.io
    - coveralls
    - popd

    # run pylint checks
    - python setup.py lint
