language: python
python:
    - 2.7
    - 3.3
    - 3.4
install:
    - pip install pytest-cov coveralls mock pylint
    - python setup.py install
script: python setup.py test
after_success:
    # upload coverage data to coveralls.io
    - coveralls

    # run pylint checks
    - python setup.py lint
