language: python
python: 2.7
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
install:
    - pip install tox coveralls pylint
    - python setup.py install
script: tox
after_success:
    # upload coverage data to coveralls.io
    - echo ${PWD}
    - coveralls

    # run pylint checks
    - python setup.py lint
