language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade pip
  - pip install --only-binary ":all:" tox codecov
script: tox -e travis
after_success:
  # upload coverage data
  - pushd .tox/travis/lib/python*/site-packages
  - codecov
  - popd
