dist: bionic
language: python
python:
- 3.6
- 3.7
cache:
  pip: true
  directories:
  - $HOME/downloads

install:
- pip install -U pip
before_script:
- git clone https://github.com/pkgcore/pkgdist.git
- cp -R pkgdist/requirements/* requirements/
- requirements/pip.sh -rrequirements/ci.txt
script: tox -e travis
after_success:
# upload coverage data
- tox -e coverage-report
- codecov

stages:
  - name: test
    if: NOT branch IN (lint, deploy)
  - name: deploy
    if: (type = api) OR (branch = deploy) OR (tag IS present)

jobs:
  include:
    # push tarball and wheels to pypi
    - stage: deploy
      sudo: required
      services:
      - docker
      env:
      - secure: bJUK+FEBax3oKhFwwAbTFbMKUpicZKjonddgMUaXrFWE0V8Mm8tL2dPBAvjOZD5xpz5YEqnspJR34VjvHVc7QwwJ+M/KECB2olh4z/CKUi5OLiQd65chHaMSRyXOveAEEeoLCbXC0UzlydpWfBQtxKUX75cFHO8FOphQE+ruoFU=
      - secure: Kb6Fb2EX9skkftvy63SDTCQSazBhn2RFVxYkSy9K1l0+qzi7dujalMuEVCwWZei6WdvpemzIvRx2lNM7Az5mOollTmLTSAUlcaaDNbO+vn4YJmXzgFoDELd+YZp1nRT1Aears/EK0P+uoAILOBfEm3kc/b7sql3upjit+khjHko=
      - CIBW_PLATFORM=linux
      - CIBW_BUILD="cp36-* cp37-*"
      - CIBW_BEFORE_BUILD="pip install -r requirements/wheel.txt -r requirements/test.txt"
      - CIBW_TEST_COMMAND="py.test {project}/tests"
      before_script:
      - git clone https://github.com/pkgcore/pkgdist.git
      - cp -R pkgdist/requirements/* requirements/
      script: pkgdist/build-dist-files.sh
      after_success:

    # push tarball to github
    - stage: deploy
      before_script:
      - git clone https://github.com/pkgcore/pkgdist.git
      - cp -R pkgdist/requirements/* requirements/
      - pip install -r requirements/sdist.txt
      script: python setup.py sdist -v
      after_success: tar -ztf dist/*.tar.gz | sort
      deploy:
        provider: releases
        api_key:
          secure: GSrtySHZ6cSz9fW/IJld/Yz/PQBVqud2Hvw9A1krFG65HfjrfC4L0koosCiO8Da99rmmuRPdMr4Y5bIMiEyOtW0TawcwMoSWEl0K+aZhRImnC0OtT2EXpxfQO6EUi2EogUiYwi9yLkUeLSHcZYkbyTSUogxgOezjvAG7DBsPgXM=
        file_glob: true
        file: dist/*.tar.gz
        skip_cleanup: true
        on:
          tags: true
