language: python
python: 3.4
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
install: pip install tox coveralls pylint
script: tox
after_success:
    # upload coverage data to coveralls.io
    - pushd .tox/${TOXENV}/lib/python*/site-packages
    - coveralls
    - popd

    # run pylint checks
    - python setup.py lint
