[build-system]
requires = [
	"wheel", "setuptools",
	"snakeoil~=0.9.3",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
